name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ================= SAST =================
      - name: Run Bandit (Python Scan)
        run: |
          pip install bandit
          bandit -r backend/

      # ================= Dependency Scan =================
      - name: Run Safety Check
        run: |
          pip install safety
          safety check

  build:
    needs: security-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Frontend
      - name: Build Frontend
        run: docker build -t cloaknote-frontend .

      # Build Backend
      - name: Build Backend
        run: docker build -t cloaknote-backend ./backend

      # ================= IMAGE SCAN =================
      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cloaknote-frontend
          format: table

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cloaknote-backend
          format: table

      # Push Images
      - name: Tag & Push Frontend
        run: |
          docker tag cloaknote-frontend ${{ secrets.DOCKER_USERNAME }}/cloaknote-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cloaknote-frontend:latest

      - name: Tag & Push Backend
        run: |
          docker tag cloaknote-backend ${{ secrets.DOCKER_USERNAME }}/cloaknote-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cloaknote-backend:latest